language: c

sudo: true
dist: focal

addons:
  apt:
    sources:
      - sourceline: 'ppa:dosemu2/ppa'
      - sourceline: 'ppa:jwt27/djgpp-toolchain'
      - sourceline: 'ppa:tkchia/build-ia16'
    packages:
      - acl
      - comcom32
      - git
      - bash
      - autoconf
      - autotools-dev
      - automake
      - coreutils
      - linuxdoc-tools
      - bison
      - flex
      - gawk
      - sed
      - libbsd-dev
      - libx11-dev
      - libxext-dev
      - libslang2-dev
      - xfonts-utils
      - libgpm-dev
      - libasound2-dev
      - libsdl2-dev
      - libsdl2-ttf-dev
      - libfontconfig1-dev
      - libsdl1.2-dev
      - ladspa-sdk
      - libfluidsynth-dev
      - libao-dev
      - libieee1284-3-dev
      - libreadline-dev
      - libjson-c-dev
      - libslirp-dev
      - binutils-dev
      - pkg-config
      - clang
      - nasm
      - python3-cpuinfo
      - python3-pexpect
      - gcc-djgpp
      - qemu-system-common
      - gdb
      - valgrind
      - gcc-ia16-elf
      - gcc-multilib
      - dos2unix
    update: true

cache:
  directories:
    - $HOME/cache

env: FDPP_KERNEL_DIR="$(pwd)/localfdpp/share/fdpp"

before_install:
  - echo "before_install"

install:
  - ./travis_build.sh

before_script:
# this acl no longer persists in Focal due to /dev/kvm management by systemd
# - sudo setfacl -m u:${USER}:rw /dev/kvm
# so we have to do this instead
  - sudo chmod 666 /dev/kvm

script:
  - ./travis_test.sh

after_script:
  - echo "after_script"
